
root = "."
tmp_dir = "tmp"

[build]
cmd = "make build & make docs"
bin = "./build/kori"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "build"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

