version: '3.8'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "redis-server --daemonize yes && redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16-alpine
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superhuman -d posthoot"]
      interval: 10s
      timeout: 5s
      retries: 5

  posthoot-server:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - app-network

volumes:
  redis-data:
  postgres-data:

networks:
  app-network:
    driver: bridge
