version: '3.8'

services:
  posthoot_redis:
    image: redis:7-alpine
    volumes:
      - posthoot_redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - posthoot_network
    healthcheck:
      test: ["CMD-SHELL", "redis-server --daemonize yes && redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  posthoot_postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - posthoot_postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - posthoot_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  posthoot_server:
    build: .
    env_file:
      - .env
    depends_on:
      posthoot_redis:
        condition: service_healthy
      posthoot_postgres:
        condition: service_healthy
    networks:
      - posthoot_network

volumes:
  posthoot_redis_data:
  posthoot_postgres_data:

networks:
  posthoot_network:
    driver: bridge
