apiVersion: v1
kind: ConfigMap
metadata:
  name: posthoot-config
  namespace: posthoot
data:
  public-url: "https://your-domain.com"
  storage-provider: "local"
  worker-concurrency: "5"
  worker-queue-size: "100"
  airley-enabled: "false"

