apiVersion: v1
kind: Pod
metadata:
  name: redis-local-proxy
  namespace: posthoot
  labels:
    app: redis-proxy
spec:
  containers:
  - name: stunnel
    image: dweomer/stunnel
    ports:
    - containerPort: 6379
      name: redis
    command:
    - stunnel
    stdin: true
    tty: true
    volumeMounts:
    - name: stunnel-config
      mountPath: /etc/stunnel
  volumes:
  - name: stunnel-config
    configMap:
      name: stunnel-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stunnel-config
  namespace: posthoot
data:
  stunnel.conf: |
    foreground = yes
    debug = 7

    [redis]
    client = yes
    accept = 6379
    connect = posthoot-valkey-serverless-siwda3.serverless.use2.cache.amazonaws.com:6379
    verifyChain = no
